from enum import Enum

class BNFType(Enum):
  PROGRAMA = 1
  DECLARACAO_LISTA = 2
  DECLARACAO = 3
  VAR_DECLARACAO = 4
  TIPO_ESPECIFICADOR = 5
  FUN_DECLARACAO = 6
  PARAMS = 7
  PARAMS_LISTA = 8
  PARAM = 9
  COMPOSTO_DECL = 10
  LOCAL_DECLARACOES = 11
  STATEMENT_LIST = 12
  STATEMENT = 13
  EXPRESSAO_DECL = 14
  SELECAO_DECL = 15
  ITERACAO_DECL = 16
  RETORNO_DECL = 17
  EXPRESSAO = 18
  VAR = 19
  SIMPLES_EXPRESSAO = 20
  RELACIONAL = 21
  SOMA_EXPRESSAO = 23
  SOMA = 24
  TERMO = 25
  MULT = 26
  FATOR = 27
  ATIVACAO = 28
  ARGS = 29
  ARG_LISTA = 30